#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportMediaMetadataWindowsService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CallCenter")]
	public partial class MediaMetaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MediaMetaDataContext() : 
				base(global::ImportMediaMetadataWindowsService.Properties.Settings.Default.CallCenterConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MediaMetaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MediaMetaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MediaMetaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MediaMetaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_cc_insert_media_metadata")]
		public int usp_cc_insert_media_metadata([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1024)")] string path, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1024)")] string contact_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1024)")] string first_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1024)")] string last_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1024)")] string group_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1024)")] string team_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1024)")] string calling_number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1024)")] string called_number, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> record_datetime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1024)")] string call_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1024)")] string reason_code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1024)")] string extension, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1024)")] string session, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1024)")] string account_no, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1024)")] string remark)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), path, contact_id, first_name, last_name, group_name, team_name, calling_number, called_number, record_datetime, call_id, reason_code, extension, session, account_no, remark);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
