//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Phatra.CallCenter.Data
{
    [MetadataType(typeof(Metadata))] 
    public partial class CallCenterGetDrilldownLoginResult
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "Username")]
            [StringLength(256, ErrorMessage = "Username must be under 256 characters.")]
            public string Username { get; set; }
            
            [Display(Name = "Account No")]
            [StringLength(50, ErrorMessage = "Account No must be under 50 characters.")]
            public string AccountNo { get; set; }
            
            [Display(Name = "Client Name T")]
            [StringLength(500, ErrorMessage = "Client Name T must be under 500 characters.")]
            public string ClientNameT { get; set; }
            
            [Display(Name = "Client Name E")]
            [StringLength(500, ErrorMessage = "Client Name E must be under 500 characters.")]
            public string ClientNameE { get; set; }
            
            [Display(Name = "Front Type Desc")]
            [StringLength(50, ErrorMessage = "Front Type Desc must be under 50 characters.")]
            public string FrontTypeDesc { get; set; }
            
            [Display(Name = "Can Trade")]
            [StringLength(20, ErrorMessage = "Can Trade must be under 20 characters.")]
            public string CanTrade { get; set; }

            #endregion
    	}

        #endregion
    }
}
