//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetWrapUpInfoResult
    {
        #region Primitive Properties
        public string CallSession { get; set; }
        public string AgentId { get; set; }
        public string CustomerPhone { get; set; }
        public string OriginalAccountNo { get; set; }
        public Nullable<decimal> OriginalClientId { get; set; }
        public Nullable<decimal> ClientId { get; set; }
        public string AccountNo { get; set; }
        public System.DateTime CallStarttime { get; set; }
        public string WrapupText { get; set; }
        public Nullable<System.DateTime> WrapupDateTime { get; set; }
        public Nullable<decimal> PoaId { get; set; }

        #endregion
    }
    
}
