//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Phatra.CallCenter.Data
{
    [MetadataType(typeof(Metadata))] 
    public partial class CallCenterGetAccountPortfolioInfoResult
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "Account")]
            [StringLength(15, ErrorMessage = "Account must be under 15 characters.")]
            public string Account { get; set; }
            
            [Display(Name = "Turnoveracc")]
            [Required(ErrorMessage = "Turnoveracc is Required.")]
            [StringLength(15, ErrorMessage = "Turnoveracc must be under 15 characters.")]
            public string Turnoveracc { get; set; }
            
            [Display(Name = "Asset Lib")]
            [StringLength(1, ErrorMessage = "Asset Lib must be under 1 characters.")]
            public string AssetLib { get; set; }
            
            [Display(Name = "Viewby")]
            [StringLength(5, ErrorMessage = "Viewby must be under 5 characters.")]
            public string Viewby { get; set; }
            
            [Display(Name = "Grpord")]
            public Nullable<int> Grpord { get; set; }
            
            [Display(Name = "Grpname")]
            [StringLength(100, ErrorMessage = "Grpname must be under 100 characters.")]
            public string Grpname { get; set; }
            
            [Display(Name = "Classord")]
            public Nullable<int> Classord { get; set; }
            
            [Display(Name = "Classcode")]
            [StringLength(5, ErrorMessage = "Classcode must be under 5 characters.")]
            public string Classcode { get; set; }
            
            [Display(Name = "Classdesc")]
            [StringLength(100, ErrorMessage = "Classdesc must be under 100 characters.")]
            public string Classdesc { get; set; }
            
            [Display(Name = "Subgrp1")]
            [StringLength(25, ErrorMessage = "Subgrp1 must be under 25 characters.")]
            public string Subgrp1 { get; set; }
            
            [Display(Name = "Grp1ord")]
            public Nullable<int> Grp1ord { get; set; }
            
            [Display(Name = "Posdate")]
            public Nullable<System.DateTime> Posdate { get; set; }
            
            [Display(Name = "Porttype")]
            [StringLength(1, ErrorMessage = "Porttype must be under 1 characters.")]
            public string Porttype { get; set; }
            
            [Display(Name = "Desk")]
            [Required(ErrorMessage = "Desk is Required.")]
            [StringLength(10, ErrorMessage = "Desk must be under 10 characters.")]
            public string Desk { get; set; }
            
            [Display(Name = "AType")]
            [Required(ErrorMessage = "AType is Required.")]
            [StringLength(1, ErrorMessage = "AType must be under 1 characters.")]
            public string AType { get; set; }
            
            [Display(Name = "Amc Code")]
            [StringLength(15, ErrorMessage = "Amc Code must be under 15 characters.")]
            public string AmcCode { get; set; }
            
            [Display(Name = "Share Code")]
            [Required(ErrorMessage = "Share Code is Required.")]
            [StringLength(50, ErrorMessage = "Share Code must be under 50 characters.")]
            public string ShareCode { get; set; }
            
            [Display(Name = "Share Codes")]
            [Required(ErrorMessage = "Share Codes is Required.")]
            [StringLength(50, ErrorMessage = "Share Codes must be under 50 characters.")]
            public string ShareCodes { get; set; }
            
            [Display(Name = "CUnit Bal")]
            public Nullable<decimal> CUnitBal { get; set; }
            
            [Display(Name = "Cavgcost")]
            public Nullable<double> Cavgcost { get; set; }
            
            [Display(Name = "Ctotcost")]
            public Nullable<decimal> Ctotcost { get; set; }
            
            [Display(Name = "Mktprice")]
            public Nullable<decimal> Mktprice { get; set; }
            
            [Display(Name = "Mktvalue")]
            public Nullable<decimal> Mktvalue { get; set; }
            
            [Display(Name = "Ugl")]
            public Nullable<decimal> Ugl { get; set; }
            
            [Display(Name = "Ugl Pct")]
            public Nullable<decimal> UglPct { get; set; }
            
            [Display(Name = "Totmkt")]
            public Nullable<decimal> Totmkt { get; set; }
            
            [Display(Name = "Weight Pct")]
            public Nullable<decimal> WeightPct { get; set; }
            
            [Display(Name = "Flag")]
            [StringLength(1, ErrorMessage = "Flag must be under 1 characters.")]
            public string Flag { get; set; }
            
            [Display(Name = "No Dec")]
            public Nullable<int> NoDec { get; set; }

            #endregion

    	}

        #endregion

    }
}
