//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Phatra.CallCenter.Data
{
    [MetadataType(typeof(Metadata))] 
    public partial class CallCenterGetClientListFromPhonenoResult
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "Phoneno")]
            [StringLength(30, ErrorMessage = "Phoneno must be under 30 characters.")]
            public string Phoneno { get; set; }
            
            [Display(Name = "Client Id")]
            public Nullable<decimal> ClientId { get; set; }
            
            [Display(Name = "Pid No")]
            [StringLength(20, ErrorMessage = "Pid No must be under 20 characters.")]
            public string PidNo { get; set; }
            
            [Display(Name = "Pid Type Desc")]
            [StringLength(100, ErrorMessage = "Pid Type Desc must be under 100 characters.")]
            public string PidTypeDesc { get; set; }
            
            [Display(Name = "Client Name T")]
            [StringLength(250, ErrorMessage = "Client Name T must be under 250 characters.")]
            public string ClientNameT { get; set; }
            
            [Display(Name = "Client Name E")]
            [StringLength(250, ErrorMessage = "Client Name E must be under 250 characters.")]
            public string ClientNameE { get; set; }
            
            [Display(Name = "Birth Date")]
            public Nullable<System.DateTime> BirthDate { get; set; }
            
            [Display(Name = "Tel Home")]
            [StringLength(100, ErrorMessage = "Tel Home must be under 100 characters.")]
            public string TelHome { get; set; }
            
            [Display(Name = "Tel Office")]
            [StringLength(100, ErrorMessage = "Tel Office must be under 100 characters.")]
            public string TelOffice { get; set; }
            
            [Display(Name = "Mobile")]
            [StringLength(100, ErrorMessage = "Mobile must be under 100 characters.")]
            public string Mobile { get; set; }
            
            [Display(Name = "Addr Mail")]
            [StringLength(400, ErrorMessage = "Addr Mail must be under 400 characters.")]
            public string AddrMail { get; set; }
            
            [Display(Name = "Contact Name T")]
            [StringLength(200, ErrorMessage = "Contact Name T must be under 200 characters.")]
            public string ContactNameT { get; set; }
            
            [Display(Name = "Contact Name E")]
            [StringLength(200, ErrorMessage = "Contact Name E must be under 200 characters.")]
            public string ContactNameE { get; set; }
            
            [Display(Name = "Contact Relationship")]
            [StringLength(250, ErrorMessage = "Contact Relationship must be under 250 characters.")]
            public string ContactRelationship { get; set; }
            
            [Display(Name = "Contact Tel Home")]
            [StringLength(100, ErrorMessage = "Contact Tel Home must be under 100 characters.")]
            public string ContactTelHome { get; set; }
            
            [Display(Name = "Contact Tel Office")]
            [StringLength(100, ErrorMessage = "Contact Tel Office must be under 100 characters.")]
            public string ContactTelOffice { get; set; }
            
            [Display(Name = "Contact Mobile")]
            [StringLength(100, ErrorMessage = "Contact Mobile must be under 100 characters.")]
            public string ContactMobile { get; set; }

            #endregion
    	}

        #endregion
    }
}
