//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetAccountInfoResult
    {
        #region Primitive Properties
        public string AccountNo { get; set; }
        public string AccountType { get; set; }
        public string JointAccount { get; set; }
        public string AccountNameT { get; set; }
        public string AccountNameE { get; set; }
        public string FcnameT { get; set; }
        public string FcnameE { get; set; }
        public string FcOfftel { get; set; }
        public string EmailEdoc { get; set; }
        public string FaxConfirm { get; set; }
        public string PidNo { get; set; }
        public string PidTypeDesc { get; set; }
        public string Remark { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }

        #endregion

    }
    
}
