//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetClientListFromPhonenoResult
    {
        #region Primitive Properties
        public string Phoneno { get; set; }
        public Nullable<decimal> ClientId { get; set; }
        public string PidNo { get; set; }
        public string PidTypeDesc { get; set; }
        public string ClientNameT { get; set; }
        public string ClientNameE { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string TelHome { get; set; }
        public string TelOffice { get; set; }
        public string Mobile { get; set; }
        public string AddrMail { get; set; }
        public string ContactNameT { get; set; }
        public string ContactNameE { get; set; }
        public string ContactRelationship { get; set; }
        public string ContactTelHome { get; set; }
        public string ContactTelOffice { get; set; }
        public string ContactMobile { get; set; }

        #endregion
    }
    
}
