//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetSearchClientResult
    {
        #region Primitive Properties
        public Nullable<decimal> ClientId { get; set; }
        public string AccountNo { get; set; }
        public string Product { get; set; }
        public string SystemCode { get; set; }
        public string JointAccount { get; set; }
        public string AccountNameT { get; set; }
        public string AccountNameE { get; set; }
        public string Trader { get; set; }
        public string PidNo { get; set; }

        #endregion
    }
    
}
