//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetAccountMutualFundResult
    {
        #region Primitive Properties
        public string AccountNo { get; set; }
        public string AmcCode { get; set; }
        public string HolderId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string StatusDesc { get; set; }
        public string HolderNameT { get; set; }
        public string HolderNameE { get; set; }

        #endregion
    }
    
}
