//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetDrilldownLoginResult
    {
        #region Primitive Properties
        public string Username { get; set; }
        public string AccountNo { get; set; }
        public string ClientNameT { get; set; }
        public string ClientNameE { get; set; }
        public string FrontTypeDesc { get; set; }
        public string CanTrade { get; set; }

        #endregion
    }
    
}
