//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetMfTranResult
    {
        #region Primitive Properties
        public string AccountNo { get; set; }
        public string HolderId { get; set; }
        public string RefNo { get; set; }
        public string AmcCode { get; set; }
        public string FundCode { get; set; }
        public string TrantypeCode { get; set; }
        public Nullable<System.DateTime> Tradedate { get; set; }
        public Nullable<decimal> AmountUnit { get; set; }
        public Nullable<decimal> AmountBaht { get; set; }
        public Nullable<int> TranStatusId { get; set; }
        public string TranStatusDesc { get; set; }

        #endregion

    }
    
}
