//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetCashTranResult
    {
        #region Primitive Properties
        public string Account { get; set; }
        public Nullable<System.DateTime> Tradedate { get; set; }
        public string Sharecodes { get; set; }
        public string Trandesc { get; set; }
        public Nullable<decimal> Amt { get; set; }

        #endregion
    }
    
}
