//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetPoaResult
    {
        #region Primitive Properties
        public decimal ClientID { get; set; }
        public string POANameT { get; set; }
        public string POAPid { get; set; }
        public string POATelNo { get; set; }
        public string ProductCode { get; set; }
        public string AccountType { get; set; }
        public string AccountNO { get; set; }
        public string Flag1 { get; set; }
        public string Flag2 { get; set; }
        public string Flag3 { get; set; }
        public string Flag4 { get; set; }
        public string Flag5 { get; set; }
        public string Flag6 { get; set; }
        public string Flag7 { get; set; }
        public string FlagOther { get; set; }
        public string DocCompleted { get; set; }
        public decimal PoaId { get; set; }
        public string POANameE { get; set; }
        public string Relationship { get; set; }

        #endregion
    }
    
}
