//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetAddrInfoResult
    {
        #region Primitive Properties
        public string PidNo { get; set; }
        public Nullable<int> AddrSeq { get; set; }
        public string AddrDesc { get; set; }
        public string TelHome { get; set; }
        public string TelOffice { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }

        #endregion

    }
    
}
