//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Phatra.CallCenter.Data
{
    [MetadataType(typeof(Metadata))] 
    public partial class CallCenterGetBankingTabStatusResult
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "Client Id")]
            public Nullable<decimal> ClientId { get; set; }
            
            [Display(Name = "GUIDStatus")]
            [StringLength(200, ErrorMessage = "GUIDStatus must be under 200 characters.")]
            public string GUIDStatus { get; set; }
            
            [Display(Name = "Reason")]
            [StringLength(200, ErrorMessage = "Reason must be under 200 characters.")]
            public string Reason { get; set; }
            
            [Display(Name = "Consent Status")]
            [StringLength(100, ErrorMessage = "Consent Status must be under 100 characters.")]
            public string ConsentStatus { get; set; }

            #endregion
    	}

        #endregion
    }
}
