//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Phatra.CallCenter.Data
{
    [MetadataType(typeof(Metadata))] 
    public partial class CallCenterGetAddrInfoResult
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "Pid No")]
            [StringLength(20, ErrorMessage = "Pid No must be under 20 characters.")]
            public string PidNo { get; set; }
            
            [Display(Name = "Addr Seq")]
            public Nullable<int> AddrSeq { get; set; }
            
            [Display(Name = "Addr Desc")]
            [StringLength(50, ErrorMessage = "Addr Desc must be under 50 characters.")]
            public string AddrDesc { get; set; }
            
            [Display(Name = "Tel Home")]
            [StringLength(100, ErrorMessage = "Tel Home must be under 100 characters.")]
            public string TelHome { get; set; }
            
            [Display(Name = "Tel Office")]
            [StringLength(100, ErrorMessage = "Tel Office must be under 100 characters.")]
            public string TelOffice { get; set; }
            
            [Display(Name = "Mobile")]
            [StringLength(100, ErrorMessage = "Mobile must be under 100 characters.")]
            public string Mobile { get; set; }
            
            [Display(Name = "Fax")]
            [StringLength(100, ErrorMessage = "Fax must be under 100 characters.")]
            public string Fax { get; set; }

            #endregion

    	}

        #endregion

    }
}
