//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetWrapupReasonResult
    {
        #region Primitive Properties
        public string ReasonCode { get; set; }
        public string ReasonDesc { get; set; }

        #endregion

    }
    
}
