//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetReminderResult
    {
        #region Primitive Properties
        public int ReminderId { get; set; }
        public string CallSession { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<decimal> ClientId { get; set; }
        public string AccountNo { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> RemindDate { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }

        #endregion
    }
    
}
