//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetQuestionVerificationResult
    {
        #region Primitive Properties
        public int PurposeId { get; set; }
        public int QuestionId { get; set; }
        public int Seqno { get; set; }
        public string QuestionDetail { get; set; }
        public string MapToHtml { get; set; }
        public bool MustAsk { get; set; }
        public string IsPoaQuestion { get; set; }

        #endregion

    }
    
}
