//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Phatra.CallCenter.Data
{
    [MetadataType(typeof(Metadata))] 
    public partial class CallCenterGetWrapupReasonResult
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "Reason Code")]
            [Required(ErrorMessage = "Reason Code is Required.")]
            [StringLength(5, ErrorMessage = "Reason Code must be under 5 characters.")]
            public string ReasonCode { get; set; }
            
            [Display(Name = "Reason Desc")]
            [Required(ErrorMessage = "Reason Desc is Required.")]
            [StringLength(1024, ErrorMessage = "Reason Desc must be under 1024 characters.")]
            public string ReasonDesc { get; set; }

            #endregion
    	}

        #endregion
    }
}
