//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetBankingTabStatusResult
    {
        #region Primitive Properties
        public Nullable<decimal> ClientId { get; set; }
        public string GUIDStatus { get; set; }
        public string Reason { get; set; }
        public string ConsentStatus { get; set; }

        #endregion

    }
    
}
