//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Phatra.CallCenter.Data
{
    [MetadataType(typeof(Metadata))] 
    public partial class CallCenterGetAccountMutualFundResult
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "Account No")]
            [StringLength(15, ErrorMessage = "Account No must be under 15 characters.")]
            public string AccountNo { get; set; }
            
            [Display(Name = "Amc Code")]
            [StringLength(15, ErrorMessage = "Amc Code must be under 15 characters.")]
            public string AmcCode { get; set; }
            
            [Display(Name = "Holder Id")]
            [StringLength(30, ErrorMessage = "Holder Id must be under 30 characters.")]
            public string HolderId { get; set; }
            
            [Display(Name = "Status Id")]
            public Nullable<int> StatusId { get; set; }
            
            [Display(Name = "Status Desc")]
            [StringLength(30, ErrorMessage = "Status Desc must be under 30 characters.")]
            public string StatusDesc { get; set; }
            
            [Display(Name = "Holder Name T")]
            [StringLength(450, ErrorMessage = "Holder Name T must be under 450 characters.")]
            public string HolderNameT { get; set; }
            
            [Display(Name = "Holder Name E")]
            [StringLength(450, ErrorMessage = "Holder Name E must be under 450 characters.")]
            public string HolderNameE { get; set; }

            #endregion
    	}

        #endregion
    }
}
