//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetAccountBankSettleResult
    {
        #region Primitive Properties
        public string AccountNo { get; set; }
        public Nullable<int> BuyPayType { get; set; }
        public string BuyPayTypeDesc { get; set; }
        public Nullable<int> AtsBuyBankId { get; set; }
        public string BankBuySname { get; set; }
        public string ATSBuyAccountName { get; set; }
        public string ATSBuyBankAccount { get; set; }
        public string ATSBuyAccountType { get; set; }
        public Nullable<int> ATSBuyBranchID { get; set; }
        public string AtsBuyBranchName { get; set; }
        public string SellPayTypeDesc { get; set; }
        public Nullable<int> AtsSellBankId { get; set; }
        public string BankSellSname { get; set; }
        public string ATSSellAccountName { get; set; }
        public string ATSSellBankAccount { get; set; }
        public string ATSSellAccountType { get; set; }
        public Nullable<int> ATSSellBranchID { get; set; }
        public string AtsSellBranchName { get; set; }
        public string AmcCode { get; set; }
        public string FundCode { get; set; }
        public string ATSBuyAccountTypeDesc { get; set; }
        public Nullable<int> SellPayType { get; set; }
        public string ATSSellAccountTypeDesc { get; set; }

        #endregion

    }
    
}
