//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetEquNetBuySellResult
    {
        #region Primitive Properties
        public string Account { get; set; }
        public Nullable<System.DateTime> Tradedate { get; set; }
        public System.DateTime Settdate { get; set; }
        public string NetDesc { get; set; }
        public string AssetType { get; set; }
        public Nullable<decimal> ClientReceive { get; set; }
        public Nullable<decimal> ClientPay { get; set; }

        #endregion

    }
    
}
