//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Phatra.CallCenter.Data
{
    [MetadataType(typeof(Metadata))] 
    public partial class CallCenterGetPoaResult
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "ClientID")]
            [Required(ErrorMessage = "ClientID is Required.")]
            public decimal ClientID { get; set; }
            
            [Display(Name = "POAName T")]
            [Required(ErrorMessage = "POAName T is Required.")]
            [StringLength(200, ErrorMessage = "POAName T must be under 200 characters.")]
            public string POANameT { get; set; }
            
            [Display(Name = "POAPid")]
            [Required(ErrorMessage = "POAPid is Required.")]
            [StringLength(20, ErrorMessage = "POAPid must be under 20 characters.")]
            public string POAPid { get; set; }
            
            [Display(Name = "POATel No")]
            [Required(ErrorMessage = "POATel No is Required.")]
            [StringLength(100, ErrorMessage = "POATel No must be under 100 characters.")]
            public string POATelNo { get; set; }
            
            [Display(Name = "Product Code")]
            [Required(ErrorMessage = "Product Code is Required.")]
            [StringLength(20, ErrorMessage = "Product Code must be under 20 characters.")]
            public string ProductCode { get; set; }
            
            [Display(Name = "Account Type")]
            [Required(ErrorMessage = "Account Type is Required.")]
            [StringLength(20, ErrorMessage = "Account Type must be under 20 characters.")]
            public string AccountType { get; set; }
            
            [Display(Name = "Account NO")]
            [Required(ErrorMessage = "Account NO is Required.")]
            [StringLength(20, ErrorMessage = "Account NO must be under 20 characters.")]
            public string AccountNO { get; set; }
            
            [Display(Name = "Flag1")]
            [Required(ErrorMessage = "Flag1 is Required.")]
            [StringLength(1, ErrorMessage = "Flag1 must be under 1 characters.")]
            public string Flag1 { get; set; }
            
            [Display(Name = "Flag2")]
            [Required(ErrorMessage = "Flag2 is Required.")]
            [StringLength(1, ErrorMessage = "Flag2 must be under 1 characters.")]
            public string Flag2 { get; set; }
            
            [Display(Name = "Flag3")]
            [Required(ErrorMessage = "Flag3 is Required.")]
            [StringLength(1, ErrorMessage = "Flag3 must be under 1 characters.")]
            public string Flag3 { get; set; }
            
            [Display(Name = "Flag4")]
            [Required(ErrorMessage = "Flag4 is Required.")]
            [StringLength(1, ErrorMessage = "Flag4 must be under 1 characters.")]
            public string Flag4 { get; set; }
            
            [Display(Name = "Flag5")]
            [Required(ErrorMessage = "Flag5 is Required.")]
            [StringLength(1, ErrorMessage = "Flag5 must be under 1 characters.")]
            public string Flag5 { get; set; }
            
            [Display(Name = "Flag6")]
            [Required(ErrorMessage = "Flag6 is Required.")]
            [StringLength(1, ErrorMessage = "Flag6 must be under 1 characters.")]
            public string Flag6 { get; set; }
            
            [Display(Name = "Flag7")]
            [Required(ErrorMessage = "Flag7 is Required.")]
            [StringLength(1, ErrorMessage = "Flag7 must be under 1 characters.")]
            public string Flag7 { get; set; }
            
            [Display(Name = "Flag Other")]
            [Required(ErrorMessage = "Flag Other is Required.")]
            [StringLength(100, ErrorMessage = "Flag Other must be under 100 characters.")]
            public string FlagOther { get; set; }
            
            [Display(Name = "Doc Completed")]
            [Required(ErrorMessage = "Doc Completed is Required.")]
            [StringLength(1, ErrorMessage = "Doc Completed must be under 1 characters.")]
            public string DocCompleted { get; set; }
            
            [Display(Name = "Poa Id")]
            [Required(ErrorMessage = "Poa Id is Required.")]
            public decimal PoaId { get; set; }
            
            [Display(Name = "POAName E")]
            [Required(ErrorMessage = "POAName E is Required.")]
            [StringLength(200, ErrorMessage = "POAName E must be under 200 characters.")]
            public string POANameE { get; set; }
            
            [Display(Name = "Relationship")]
            [Required(ErrorMessage = "Relationship is Required.")]
            [StringLength(100, ErrorMessage = "Relationship must be under 100 characters.")]
            public string Relationship { get; set; }

            #endregion

    	}

        #endregion

    }
}
