//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Phatra.CallCenter.Data
{
    [MetadataType(typeof(Metadata))] 
    public partial class CallCenterGetReminderResult
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "Reminder Id")]
            [Required(ErrorMessage = "Reminder Id is Required.")]
            public int ReminderId { get; set; }
            
            [Display(Name = "Call Session")]
            [StringLength(128, ErrorMessage = "Call Session must be under 128 characters.")]
            public string CallSession { get; set; }
            
            [Display(Name = "Customer Phone")]
            [StringLength(128, ErrorMessage = "Customer Phone must be under 128 characters.")]
            public string CustomerPhone { get; set; }
            
            [Display(Name = "Client Id")]
            public Nullable<decimal> ClientId { get; set; }
            
            [Display(Name = "Account No")]
            [StringLength(15, ErrorMessage = "Account No must be under 15 characters.")]
            public string AccountNo { get; set; }
            
            [Display(Name = "Details")]
            public string Details { get; set; }
            
            [Display(Name = "Remind Date")]
            public Nullable<System.DateTime> RemindDate { get; set; }
            
            [Display(Name = "Is Cancelled")]
            public Nullable<bool> IsCancelled { get; set; }
            
            [Display(Name = "Created Date")]
            public Nullable<System.DateTime> CreatedDate { get; set; }
            
            [Display(Name = "Created User")]
            [StringLength(20, ErrorMessage = "Created User must be under 20 characters.")]
            public string CreatedUser { get; set; }
            
            [Display(Name = "Updated Date")]
            public Nullable<System.DateTime> UpdatedDate { get; set; }
            
            [Display(Name = "Updated User")]
            [StringLength(20, ErrorMessage = "Updated User must be under 20 characters.")]
            public string UpdatedUser { get; set; }

            #endregion

    	}

        #endregion

    }
}
