//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Phatra.CallCenter.Data
{
    [MetadataType(typeof(Metadata))] 
    public partial class CallCenterGetCashTranResult
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "Account")]
            [StringLength(15, ErrorMessage = "Account must be under 15 characters.")]
            public string Account { get; set; }
            
            [Display(Name = "Tradedate")]
            public Nullable<System.DateTime> Tradedate { get; set; }
            
            [Display(Name = "Sharecodes")]
            [StringLength(30, ErrorMessage = "Sharecodes must be under 30 characters.")]
            public string Sharecodes { get; set; }
            
            [Display(Name = "Trandesc")]
            [StringLength(100, ErrorMessage = "Trandesc must be under 100 characters.")]
            public string Trandesc { get; set; }
            
            [Display(Name = "Amt")]
            public Nullable<decimal> Amt { get; set; }

            #endregion
    	}

        #endregion
    }
}
