//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetProfileResult
    {
        #region Primitive Properties
        public string PidNo { get; set; }
        public string PidTypeDesc { get; set; }
        public string ClientNameT { get; set; }
        public string ClientNameE { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string NationCode { get; set; }
        public string NationDesc { get; set; }
        public string TelHome { get; set; }
        public string TelOffice { get; set; }
        public string Mobile { get; set; }
        public string FatcaStatus { get; set; }
        public string AddrMail { get; set; }
        public string ContactNameT { get; set; }
        public string ContactNameE { get; set; }
        public string ContactRelationship { get; set; }
        public string ContactTelHome { get; set; }
        public string ContactTelOffice { get; set; }
        public string ContactMobile { get; set; }
        public string MasterPoa { get; set; }
        public string CardExpireWithin { get; set; }
        public string FATCATypeDesc { get; set; }
        public Nullable<System.DateTime> CardExpireDate { get; set; }
        public string CardExpireInfo { get; set; }
        public string AddrRegister { get; set; }
        public string SSUFlag { get; set; }
        public string AgreementType { get; set; }

        #endregion

    }
    
}
