//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class CallCenterGetMissedCallListResult
    {
        #region Primitive Properties
        public string CustomerPhone { get; set; }
        public Nullable<int> Priority { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> CallStartTime { get; set; }
        public Nullable<decimal> ClientId { get; set; }

        #endregion

    }
    
}
