//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Phatra.CallCenter.Data
{
    [MetadataType(typeof(Metadata))] 
    public partial class RefGetPurposeVerificationsResult
    {
        #region Metadata
    
    	/// <summary>
    	/// Metadata internal class used for Data Annotations
    	/// </summary>
    	internal class Metadata
        {
            #region Primitive Properties
            
            [Display(Name = "Purpose Id")]
            [Required(ErrorMessage = "Purpose Id is Required.")]
            public int PurposeId { get; set; }
            
            [Display(Name = "Purpose Desc")]
            [StringLength(256, ErrorMessage = "Purpose Desc must be under 256 characters.")]
            public string PurposeDesc { get; set; }
            
            [Display(Name = "Min Ask Quest")]
            public Nullable<int> MinAskQuest { get; set; }
            
            [Display(Name = "Active")]
            public Nullable<bool> Active { get; set; }
            
            [Display(Name = "Updated Date")]
            public Nullable<System.DateTime> UpdatedDate { get; set; }
            
            [Display(Name = "Updated By")]
            [StringLength(256, ErrorMessage = "Updated By must be under 256 characters.")]
            public string UpdatedBy { get; set; }
            
            [Display(Name = "Min Pass Person Quest")]
            public Nullable<int> MinPassPersonQuest { get; set; }
            
            [Display(Name = "Min Pass Poa Quest")]
            public Nullable<int> MinPassPoaQuest { get; set; }

            #endregion
    	}

        #endregion
    }
}
