//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Phatra.CallCenter.Data
{
    public partial class RefGetPurposeVerificationsResult
    {
        #region Primitive Properties
        public int PurposeId { get; set; }
        public string PurposeDesc { get; set; }
        public Nullable<int> MinAskQuest { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> MinPassPersonQuest { get; set; }
        public Nullable<int> MinPassPoaQuest { get; set; }

        #endregion

    }
    
}
